const defaultSubmission = {
  project_id: null,
  survey_province: null,
  district_name: null,
  surveyors_code: null,
  surveyors_name: null,
  nahya_number: null,
  kbl_guzar_number: null,
  village_name: null,
  province_code: null,
  city_name: null,
  city_code: null,
  district_code: null,
  nan_guzar_number: null,
  block_number: null,
  house_number: null,
  area_representative_name: null,
  area_representative_phone: null,
  consent: null,

  number_families: null,
  household_size: null,
  hoh_disable: null,
  hof_or_interviewee: null,

  hoh_name: null,
  hoh_father_name: null,
  hoh_grandfather_name: null,
  hoh_phone_number: null,
  does_hoh_have_nic: null,
  hoh_nic_number: null,
  hoh_nic_photo: null,
  hoh_sex: null,
  hoh_age: null,

  interviewee_hof_relation: null,
  inter_name: null,
  inter_father_name: null,
  inter_grandfather_name: null,
  inter_phone_number: null,
  does_inter_have_nic: null,
  inter_nic_number: null,
  inter_nic_photo: null,
  inter_sex: null,
  inter_age: null,

  female_0_1: null,
  male_0_1: null,
  female_1_5: null,
  male_1_5: null,
  female_6_12: null,
  male_6_12: null,
  female_13_17: null,
  male_13_17: null,
  female_18_30: null,
  male_18_30: null,
  female_30_60: null,
  male_30_60: null,
  female_60_above: null,
  male_60_above: null,

  hof_ethnicity: null,
  ethnicity_other: null,

  province_origin: null,
  district_origin: null,

  status: null,

  year_idp: null,
  idp_reason: null,
  idp_securtiy_reason: null,
  natural_disaster_reason: null,
  other_reason: null,

  year_returnee: null,
  migrate_country: null,
  migrate_country_other: null,
  migration_reason: null,
  migration_reason_security: null,
  migration_reason_natural_disaster: null,
  migration_reason_other: null,
  duration_Household_living_there: null,
  date_return_home_country: null,
  entry_borders: null,
  return_document_have: null,
  type_return_document: null,
  type_return_document_number: null,
  type_return_document_date: null,
  type_return_document_photos: [],
  household_get_support_no: null,
  household_get_support: null,
  household_get_support_yes: null,
  organization_support: null,
  reason_return: null,
  return_reason_force: null,
  return_reason_voluntair: null,

  large_Household: null,
  disable_member: null,
  physical_disable: null,
  mental_disable: null,
  chronic_disable: null,
  drug_addicted: null,
  conditional_women: null,
  conditional_women_pregnant: null,
  conditional_women_breastfeeding_mother: null,
  conditional_women_widow: null,

  access_civil_documentation_male_tazkira: null,
  access_civil_documentation_male_birthcertificate: null,
  access_civil_documentation_male_marriagecertificate: null,
  access_civil_documentation_male_departationcard: null,
  access_civil_documentation_male_drivinglicense: null,

  access_civil_documentation_female_tazkira: null,
  access_civil_documentation_female_birthcertificate: null,
  access_civil_documentation_female_marriagecertificate: null,
  access_civil_documentation_female_departationcard: null,
  access_civil_documentation_female_drivinglicense: null,

  house_owner: null,
  inter_name_owner: null,
  inter_father_name_owner: null,
  inter_phone_number_owner: null,
  does_inter_have_nic_owner: null,
  inter_nic_number_owner: null,
  inter_nic_photo_owner: null,
  type_tenure_document: null,
  house_owner_myself: null,
  house_document_number: null,
  house_document_date: null,
  house_document_photos: [],
  duration_lived_thishouse: null,

  materials_house_constructed: null,
  issues_current_house: [],
  house_adequate_family_size: null,
  house_adequate_family_size_no: null,
  house_adequate_family_size_no_other: null,
  made_housing_improvement: null,
  made_housing_improvement_yes: null,
  received_humanitarian_assistance: null,
  received_humanitarian_assistance_type: null,
  received_humanitarian_assistance_org: null,
  shelter_support_received: null,
  shelter_support_received_yes: null,
  shelter_support_received_yes_other: null,
  rate_need_shelter_repair: null,
  surveyor_observation_current_house: null,
  received_humanitarian_assistance_org: null,

  house_problems_area_photos: [
    {
      current_house_problem_title: null,
      current_house_problem_photo: null,
    },
  ],

  drinkingwater_main_source: null,
  type_water_source: null,
  water_source_distance: null,
  water_source_route_safe: null,
  water_source_route_safe_no: null,
  water_collect_person: null,
  water_quality: null,
  water_point_photo: null,
  type_toilet_facilities: null,
  access_sanitation_photo: null,

  access_education: null,
  access_school: null,
  type_school: null,
  nearest_school: null,
  access_school_university: null,
  access_school_madrasa: null,
  Household_members_attend_school_present: null,
  members_attend_school_no: null,
  members_attend_school_yes_boys: null,
  members_attend_school_yes_girls: null,
  Household_members_attend_madrasa_present_howmany: null,
  members_attend_madrasa_no: null,
  members_attend_madrasa_yes_boys: null,
  members_attend_madrasa_yes_girls: null,
  Household_members_attend_university_present: null,
  litrate_Household_member: null,
  number_male_child_Household: null,
  number_female_child_Household: null,
  access_education_photo: null,
  access_education_no: null,

  access_health_services: null,
  health_facilities_type: null,
  health_service_distance: null,
  health_service_distance_no: null,
  health_facility_have_female_staff: null,
  health_challanges: null,
  health_challanges_other: null,
  access_health_photo: null,

  type_access_road: null,
  access_road_photo: null,

  how_access_electricity: null,
  energy_cooking: null,

  days_inweek_eaten_cereal: null,
  days_inweek_eaten_pulse: null,
  days_inweek_eaten_vegetables: null,
  days_inweek_eaten_fruits: null,
  days_inweek_eaten_animal: null,
  days_inweek_eaten_dairy: null,
  days_inweek_eaten_oil: null,
  days_inweek_eaten_sugar: null,
  days_inweek_eaten_bread: null,
  food_cerel_source: null,

  number_days_nothave_enough_food_less_expensive: null,
  number_days_nothave_enough_food_barrow: null,
  number_days_nothave_enough_food_limit_portion: null,
  number_days_nothave_enough_food_restrict_sonsumption: null,
  number_days_nothave_enough_food_reduce_meals: null,
  household_stocks_cereals: null,
  market_place: null,
  marketplace_distance: null,

  community_avalibility: null,
  community_center_photo: null,
  community_org_female: null,
  community_org_male: null,
  Household_member_participate: null,
  Household_member_participate_yes: null,

  Household_main_source_income: null,
  women_engagement_income: null,
  average_Household_monthly_income: null,
  improve_livelihoods: null,
  improve_livelihoods_other: null,
  future_families_preference: null,
  local_integration_details: null,
  local_integration_other: null,
  do_you_have_land: null,
  do_you_have_land_yes: null,
  debt: null,
  repaying_load_yes: null,

  members_have_skills: null,
  type_skills: null,
  type_skills_other: null,
  skills_want_learn: null,

  relocate_another_place_by_government: null,
  reason_notwantto_relocate: null,
  relocate_minimum_condition: null,
  relocate_another_place_by_government: null,
  relocate_another_place_by_government: null,

  receive_assistance: null,
  type_assistance: null,
  assistance_provided_by: null,

  infrastructure_services_settlement: [],

  field_name: null,
  latitude: null,
  longitude: null,
  altitude: null,
  accuracy: null,
  photo_interviewee: null,
  photo_house_building: null,
  photo_house_door: null,
  photo_enovirment: null,
  photo_other: null,
  remarks: null,
};

export default defaultSubmission;
